import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(root, "src", "host.mjs");
const outputDir = path.join(root, "build");
const outputPath = path.join(outputDir, "host.cjs");

let source = fs.readFileSync(sourcePath, "utf8");

const replacements = [
  [/import crypto from "node:crypto";/, 'const crypto = require("node:crypto");'],
  [/import fs from "node:fs";/, 'const fs = require("node:fs");'],
  [/import os from "node:os";/, 'const os = require("node:os");'],
  [/import path from "node:path";/, 'const path = require("node:path");'],
  [/import \{ createRequire \} from "node:module";\r?\n/, ""],
  [/import \{ fileURLToPath \} from "node:url";\r?\n/, ""],
  [/import QRCode from "qrcode";/, 'const QRCode = require("qrcode");'],
  [/const __dirname = path\.dirname\(fileURLToPath\(import\.meta\.url\)\);/, ""],
  [/const require = createRequire\(import\.meta\.url\);/, ""]
];

for (const [pattern, replacement] of replacements) {
  source = source.replace(pattern, replacement);
}

source = [
  '"use strict";',
  "// Generated by scripts/prepare-pkg-cjs.mjs. Do not edit directly.",
  source
].join("\n");

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(outputPath, source, "utf8");
console.log(`Wrote ${path.relative(root, outputPath)}`);
